### ISSUE TITLE
JUnit XML test results not displayed

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-web#102]
The docs state that "Cirrus CI supports parsing artifacts in order to extract information that can be presented in the UI for better user experience", and specifically mentions support for JUnit XML files. After generating JUnit XML files using `pytest`, I don't notice any particular difference in the UI except for the ability to download the XML file. What kind of "better user experience" is expected when a JUnit XML file is parsed?

**Comment by fkorotkov** [comment]
Please check this blog post: https://medium.com/cirruslabs/github-annotations-support-227d179cde31

Ideally once there are failing tests, Cirrus will add annotations right in GitHub UI.

**Comment by connorbrinton** [comment]
Got it. I wasn't seeing the test results because:
* I hadn't yet created a pull request, since I wasn't ready to share my changes yet and
* The failing tests were not modified in the changes, so they wouldn't have shown up in the "Files Changed" tab anyways

I created a pull request adding a link to the above blog post to the Cirrus CI docs:
https://github.com/cirruslabs/cirrus-ci-docs/pull/410

**Comment by fkorotkov** [comment]
Cool. Seems it answered your question so I'm closing this issues. Thanks for updating the docs!
