### ISSUE TITLE
Tasks not starting

### ISSUE THREAD

**Issue by asomers** [cirruslabs/cirrus-ci-web#104]
My latest PR's tasks haven't started after more than 12 hours.  I tried restarting them to no avail.  This PR changed nothing in my Cirrus configuration, so I don't think that's the problem.  The Cirrus status page shows nothing that indicates what might be the problem.  Could you please help?
https://github.com/asomers/mockall/pull/22
https://cirrus-ci.com/task/6700574844649472

**Comment by RDIL** [comment]
Hey @asomers!

Sadly, we are having Kubernetes cluster issues.  I'm not sure when it will be fixed.  They are working on it though.

**Comment by asomers** [comment]
Thanks for letting me know.  Is there a status page or tracking issue I should be following?

**Comment by RDIL** [comment]
Cirrus CI has [an official Twitter page](https://twitter.com/cirrus_labs) where downtime notices and product updates are posted.

**Comment by asomers** [comment]
Gracias.

**Comment by RDIL** [comment]
De nada.
