### ISSUE TITLE
rust-lang/libc builds are timing out

### ISSUE THREAD

**Issue by gnzlbg** [cirruslabs/cirrus-ci-web#105]
For example, see here: https://cirrus-ci.com/build/5121064810577920

It appears that the builds start executing, but never finish, and I can't access any logs. They usually finish in ~4min.

**Comment by RDIL** [comment]
Hey @gnzlbg!

Sadly, we are having Kubernetes cluster issues. I'm not sure when it will be fixed. They are working on it though.

**Comment by gnzlbg** [comment]
Roger that, thank you for the quick reply. 

I've canceled the builds. Could you let us know when the issues are resolved so that we can retry ?

**Comment by RDIL** [comment]
I'll ping you once everything is back online :)

**Comment by RDIL** [comment]
@gnzlbg see #414

**Comment by fkorotkov** [comment]
The issue is resolved now

**Comment by gnzlbg** [comment]
Thank you!
