### ISSUE TITLE
Task timeline lacks timing information 😔

### ISSUE THREAD

**Issue by aslushnikov** [cirruslabs/cirrus-ci-web#11]
Consider the following task timeline (link: https://cirrus-ci.com/task/5073269292007424)

![image](https://user-images.githubusercontent.com/746130/37499953-e437544a-2883-11e8-9211-8b75063ab5b1.png)

- can we have "Scheduled in" and "Finished in" as a part of the colorful timeline down? It currently says only "executing", but could've share much more information, e.g. all the timings for all the parts
- what are the "container.." and "DISPLAY:99" bubbles below timeline? Tooltips would help me to understand. They also look like they're clickable, but they aren't.

**Comment by fkorotkov** [comment]
I've adde a tooltip to the progress bar with all duration for all the states of a task.

The `container...` and other chips represent unique labels of the task. `container` shows that the task is executed in a container image from `gcr.io/...` registry. `DISPLAY` shows that this environment variable is defined. You can also see them on build pages where there is a list of tasks. Such labels can help to distinguish tasks with the same name when someone uses [matrix modification](http://cirrus-ci.org/guide/writing-tasks/#matrix-modification) like this:

```
test_task:
  container:
    matrix:
      image: node:latest
      image: node:8.3.0
  test_script: yarn run test
```

In the example above the only way to distinguish tasks is by having different `container:node:latest` and `container:node:8.3.0` labels in the UI.
