### ISSUE TITLE
Cannot read property 'id' of null

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-web#114]
I've started to occasionally get this error on the home page of the Cirrus CI app. It might be related to the fact that a ton of automatically triggered builds were started within the past hour or so. Besides that, I'm not really sure what the root cause might be though.

<img width="1678" alt="Screenshot 2019-09-16 20 00 40" src="https://user-images.githubusercontent.com/1848731/65001297-d0338780-d8bc-11e9-9989-d901ba50bd61.png">

Let me know if I can get any other debugging information for you 😄

**Comment by connorbrinton** [comment]
Something is definitely up though, even when I have managed to load the home page this evening, it doesn't show any recent builds, even though I'm pretty sure there have been a good number. I'm having trouble accessing any repository's info though, so I can't verify very easily (I'm getting "Page not found! Go home?" a lot and an empty "Active repositories" sidebar most times I try to open it)

<img width="1678" alt="Screenshot 2019-09-16 20 05 53" src="https://user-images.githubusercontent.com/1848731/65001451-80a18b80-d8bd-11e9-918a-153e5756bd8d.png">

**Comment by fkorotkov** [comment]
Yeah, there is an [incident is going on](https://twitter.com/cirrus_labs/status/1173741631054458880). Should recover soon.
