### ISSUE TITLE
Button to cancel all tasks in a build

### ISSUE THREAD

**Issue by connorbrinton** [cirruslabs/cirrus-ci-web#117]
In order to cancel all tasks in a build, I think it's currently necessary to click on each task individually and click "Cancel". Combined with the lack of `Cmd + click` (or `Ctrl + click` on other OSes) support in the Cirrus CI interface, this makes cancelling all tasks in a build very difficult. Would it be possible to add a button to the build page that cancels all tasks in the build?

**Comment by RDIL** [comment]
I gave it a shot in #134

**Comment by RDIL** [comment]
I’m going to add this later today.

**Comment by fkorotkov** [comment]
@RDIL let's do a separate PR and not try to squeeze bunch of changes. 😅

**Comment by RDIL** [comment]
Yup that was what I was going to do.

**Comment by MarcoFalke** [comment]
I see there was commit eb03213aaec955b6f958626fbd28a379ed22b93f, but I am wondering what the current status is
