### ISSUE TITLE
A title for the build task❓

### ISSUE THREAD

**Issue by aslushnikov** [cirruslabs/cirrus-ci-web#12]
Example URL: https://cirrus-ci.com/task/5073269292007424

![image](https://user-images.githubusercontent.com/746130/37500057-85f8598c-2884-11e8-9998-8b843c96b853.png)

I usually have 2-5 tabs with builds open in the browser, and it's hard to quickly find the one i'm interested in. Although all the necessary information is there, it's not easily distinguishable.

It would help a lot if the commit title is somewhere in the top, together with the task name.

**Comment by fkorotkov** [comment]
What do you think about reversing the order of top chips? Kind of in order of importance: from task name down to repository name.

![image](https://user-images.githubusercontent.com/989066/37620029-81ed6318-2b91-11e8-9a0c-28112ca086f4.png)

**Comment by aslushnikov** [comment]
> What do you think about reversing the order of top chips?

@fkorotkov it will improve things slightly. 

>  Kind of in order of importance: from task name down to repository name.

💡: how about allocating more visual space for the more important bits? This will make builds from different projects to be visually very distinct (e.g. if there's a huge header with project name in the top). 

Similarly, if commit messages are given more space, padding and bigger font, different builds of the same project would be quite easily distinguishable from a single glance.

Another thing: for a build, i usually care what's the position of the commit inside the branch. Oh it would be so nice if there's a list of all commits/builds for the branch somewhere on the screen with an arrow pointing to the one currently displayed...

**Comment by fkorotkov** [comment]
This UI was changed a while ago to have two distinct groups of chips with information only about commit and only about execution
