### ISSUE TITLE
Examine usage of assets

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#136]
Looking at the `index.html`, it seems a lot of different libraries are used, not all of which I imagine are needed.

* I don't think jQuery is used
  * possibly needed for twbs
* ~~Why is popper here?  Doesn't MUI load it in if its needed?~~
* ~~Should we really load the stripe JS on every page? Yes it is async, which is good, but still.~~

Related: #135

**Comment by fkorotkov** [comment]
AFAIK Bootstrap is still using jQuery

**Comment by RDIL** [comment]
Just did some research and found [this](https://www.w3schools.com/bootstrap/bootstrap_get_started.asp#midcontentadcontainer).  Are we using the JS side of things?

**Comment by RDIL** [comment]
Fixed now.
