### ISSUE TITLE
Deploys broken

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#139]
Needs investigation - it seems Cirrus is failing to deploy the frontend dashboard.

The build logs look fine so maybe it’s just docker cloud or GCP

Ref: https://github.com/cirruslabs/cirrus-ci-web/pull/137#issuecomment-565444526

**Comment by fkorotkov** [comment]
What kind of deploys?

**Comment by RDIL** [comment]
Deploys of the web frontend, remember https://github.com/cirruslabs/cirrus-ci-web/pull/137#issuecomment-565444526?

**Comment by fkorotkov** [comment]
I remember but other people reading this issue don't have context so please be more descriptive ;-)

**Comment by RDIL** [comment]
Fixed

**Comment by fkorotkov** [comment]
The deploys will remain manual for foreseeable future to make sure nothing bad is deployed automatically.

**Comment by RDIL** [comment]
I will set up snapshot tests to aid in making sure bad deploys dont happen

**Comment by fkorotkov** [comment]
Sounds good! That would be awesome!
