### ISSUE TITLE
Ability to remove projects from Cirrus?

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-ci-web#144]
At this point I have a few projects that have either been deleted or renamed, but still show up on https://cirrus-ci.com/github/duckinator/ .

It'd be really nice if there were a way to remove those.

I'd be okay with either of:

1. A way to have it check all the repos under an org/user, and remove/hide ones that no longer exist.
2. A way to manually remove/hide an individual repo.

**Comment by duckinator** [comment]
As an aside, was there a time in the past where Cirrus CI tried to run stuff for all repos it had access to, even if there was no `.cirrus.yml`? Most of the repos I'd like to remove are ones that have never had a `.cirrus.yml` to start with, and I don't know why Cirrus tried to do anything with them.

**Comment by duckinator** [comment]
Over a year and a half later, it turns out I have closer to a dozen projects that I'd like to remove from Cirrus CI (they either don't exist, got renamed, or they aren't using CI at all). Is there any way to remove them?

**Comment by RDIL** [comment]
To be honest, I think you would need to ask Fedor to remove them from the database.  Not sure if anything else can be done.

**Comment by duckinator** [comment]
I somehow missed that response for over a year, until I came to open this issue and found out I'd already done so. 😅 

@fkorotkov is there a chance this functionality could be added or the following projects could be removed? (They're all now-nonexistent, never had a Cirrus CI config to start with, got renamed, or have been abandoned.)

- duckinator/the-whale
- duckinator/rgdev-python
- duckinator/reproduce
- duckinator/radio
- duckinator/possum
- duckinator/jellyfin-chromium
- duckinator/cirrus-ci-issue-541-testcase
- duckinator/cadence
- duckinator/build-image
- duckinator/bork-container
- duckinator/beseech
- duckinator/asset-manager
- duckinator/stream.boop.ws
