### ISSUE TITLE
Jobs not running or not reporting back to GitHub

### ISSUE THREAD

**Issue by esvinson** [cirruslabs/cirrus-ci-web#145]
Seeing issues where the cirrus tasks aren't report that they competed back to GitHub as well as issues with starting new tasks.

The task just sits in the 'Triggered' status.  Sitting like that for 8+ minutes so far.

<img width="154" alt="Screen Shot 2020-01-17 at 12 02 20 PM" src="https://user-images.githubusercontent.com/195006/72638823-8073d400-3921-11ea-99b3-a3410d0ad323.png">

Are you seeing any issues on your end?

**Comment by RDIL** [comment]
Can you link the task?

**Comment by fkorotkov** [comment]
Yes, just got an alert about delays to update statuses back to GitHub. Looking into it.

**Comment by esvinson** [comment]
> Can you link the task?

https://cirrus-ci.com/build/5417007185133568   (the one not reporting back)
https://cirrus-ci.com/build/5936277958688768  (the one that spent 15 minutes in the Triggered status)

**Comment by fkorotkov** [comment]
Should be fixed now. Monitoring the situation still.

**Comment by esvinson** [comment]
> Should be fixed now. Monitoring the situation still.

Thank you!
