### ISSUE TITLE
Html job output

### ISSUE THREAD

**Issue by JoelEinbinder** [cirruslabs/cirrus-ci-web#15]
It would be super cool if I could provide an html file as the output of my tests, in addition to the terminal output. I would use this to display the output from pixel tests, and the detailed coverage information about what code ran.

**Comment by fkorotkov** [comment]
That's a great idea! Do you want to display it within a task page or as a separate standalone html page?

**Comment by aslushnikov** [comment]
Standalone with a small header (like [jsbin does](https://output.jsbin.com/kayaxug)) would work very well!

**Comment by fkorotkov** [comment]
I'll see how it can be safely done to avoid XSS and will report back.

**Comment by fkorotkov** [comment]
It's now can be achieved though annotations and artifacts: https://medium.com/cirruslabs/github-annotations-support-227d179cde31
