### ISSUE TITLE
Consider ejecting from CRA

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#152]
CRA's presets and config isn't bad, but there are some features that I personally want to implement that I can't because CRA is in the way.

If we eject, we can make our already-huge bundle smaller, reduce the number of dependencies needed, remove any features that we aren't using, e.g. Sass support, speed up the webpack build process, and more.  Sure, we would have to check the (javascript and es5) configurations and scripts into Git, but I think that by ejecting we would be able to customize a lot more stuff, so I'm opening this issue for discussion.

**Comment by fkorotkov** [comment]
IMO at the moment feature development is more important than optimizations and tweaking. Build speed and bundle size with the current code splitting is not that bad. Don't see a reason right now to focus on it. 🤷‍♂

**Comment by RDIL** [comment]
All right then
