### ISSUE TITLE
View build time + compute credits usage over time

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-ci-web#153]
A few distinct-but-related things would be nice:

1. A graph that shows how much time is spent on builds each day.
2. A graph that shows how many compute credits are used each day.
3. Ordered list of top `$N` (w/e number y'all think is reasonable) projects using the most of build time + credits during the last month. (Probably ordered most -> least.)

I'm thinking basically something like Netlify's "insights" page, but with both build time + compute credits:

![Screenshot_20200210_211815](https://user-images.githubusercontent.com/39698/74206846-1f52ce00-4c4b-11ea-86b9-c3a9ddd1baa8.png)

**Comment by fkorotkov** [comment]
You can see something similar for a repository on Metrics page.

![image](https://user-images.githubusercontent.com/989066/74238898-bf891100-4ca4-11ea-86e8-01582ed416ec.png)
