### ISSUE TITLE
No SKIPPED status in the crirrus graphql BuildStatus

### ISSUE THREAD

**Issue by keyonghan** [cirruslabs/cirrus-ci-web#157]
Not sure if there is any other missing statuses in current BuildStatus. But SKIPPED is missing for sure.

**Comment by keyonghan** [comment]
https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql#L120
It current has only the following:
'''enum BuildStatus {
  CREATED
  NEEDS_APPROVAL
  TRIGGERED
  EXECUTING
  FAILED
  COMPLETED
  ABORTED
  ERRORED
}'''

**Comment by fkorotkov** [comment]
@keyonghan only tasks can be in `SKIPPED` status. Build will be in `COMPLETED`.

**Comment by fkorotkov** [comment]
See https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql#L569-L579

**Comment by keyonghan** [comment]
Ah. thank!
