### ISSUE TITLE
How are "previous runs" sorted?

### ISSUE THREAD

**Issue by aslushnikov** [cirruslabs/cirrus-ci-web#16]
Link: https://cirrus-ci.com/task/5633878404366336

I have a few re-tries of the task, but I don't understand how these runs are sorted. Which one is my last one?

![image](https://user-images.githubusercontent.com/746130/38150752-664bb5f6-3415-11e8-9083-9b6e45004255.png)

**Comment by fkorotkov** [comment]
Fixed in df1a0afe801d74c694c3dc766bcf77e31cfc76c7. Now it shows all other run + time when they were created.
