### ISSUE TITLE
GitHubOrganizationRepositoryList broken

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#161]
It just displays an empty table.

**Comment by fkorotkov** [comment]
Links are more details in general to reproduce are always appreciated. ;-)

**Comment by RDIL** [comment]
@fkorotkov for example https://cirrus-ci.com/github/area4lib should show the `area4` repository, but it doesn't

**Comment by RDIL** [comment]
This works now for some reason.  Closing.
