### ISSUE TITLE
Show Task's timeline in a list

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-web#172]
Right now [build's page](https://cirrus-ci.com/build/6180886766944256) shows just a list of tasks in an order of task declaration in `.cirrus.yml` file.

![image](https://user-images.githubusercontent.com/989066/81438611-0f0f9980-913b-11ea-80d8-9ba84270e8ad.png)

And each [task](https://cirrus-ci.com/task/5083846792183808) has a timeline with durations of each status (`CREATED`, `TRIGGERED`, etc.)

![image](https://user-images.githubusercontent.com/989066/81438695-2b133b00-913b-11ea-9cc5-fd7aeb8e7398.png)

It will be nice to start sorting tasks based on their [`triggeredTimestamp`](https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql#L487) and show a relative timeline of durations to overall duration of a build. Something like that:

![image](https://user-images.githubusercontent.com/989066/81438804-5dbd3380-913b-11ea-87fc-f6e210b30112.png)

**Comment by squidfunk** [comment]
__Estimate: 8.0h__

It should be pretty straight forward to draw something like that using SVG, but again, the problem probably lies in the details. We need to think about edge cases with long task lists (i.e. many tasks), long builds (sticky task titles while scrolling horizontally?), that's what makes it challenging + thinking for where we could integrate this.

Maybe consider another alternative from CircleCI, which is not a timeline, but shows dependencies, still:

![wf-header](https://user-images.githubusercontent.com/932156/82296959-42abb880-99b2-11ea-96f2-f56594a59a27.png)
