### ISSUE TITLE
Show pending status instead of last result

### ISSUE THREAD

**Issue by aslushnikov** [cirruslabs/cirrus-ci-web#18]
Consider the following screen: 

![image](https://user-images.githubusercontent.com/746130/38156478-01b12ce8-3433-11e8-8595-26a6a679214a.png)

Note: the chip is shown as "red", even though I restarted all the failing tasks.
It will be very helpful if the chip is dynamic, e.g. has colors that correspond to the stage of the currently running task.

**Comment by fkorotkov** [comment]
It should be dynamic. It subscribes to updates of the build: https://github.com/cirruslabs/cirrus-ci-web/blob/master/src/components/chips/BuildStatusChip.js#L27-L35

Maybe WebSocket closed but there is a retry... Will see how we can improve stabiity of subscription more.
