### ISSUE TITLE
Allow linking to build status based on commit hash

### ISSUE THREAD

**Issue by DanTup** [cirruslabs/cirrus-ci-web#23]
Currently the links to build results are not guessable, so for something like the [Flutter build dashboard](https://flutter-dashboard.appspot.com/build.html) the links in the Cirrus column all go to the same place and you have to scroll through to find the failed build.

It'd be great if we could construct links with the hash of the commit to link directly (I think we could also get this from the GH status API, but this would be simpler and useful to many people).

**Comment by fkorotkov** [comment]
Was fixed by 212a5aaeb62db621b8cace37a7191bb480b41811
