### ISSUE TITLE
Consider changing the "running" icons to not be green

### ISSUE THREAD

**Issue by DanTup** [cirruslabs/cirrus-ci-web#24]
Quite a few times I've clicked through to a build thinking it had passed and noticed it was still running. When I click back, I realise the green icon I noticed was actually the "running" icon!

![screen shot 2018-08-22 at 10 54 15 am](https://user-images.githubusercontent.com/1078012/44456981-e1e32680-a5f9-11e8-8566-3b498bb057dd.png)

I think it would be better if this icon was not green (maybe orange/yellow?). I know it looks really obviously different when you look at it consciously, but I've misread it more than a few times now. Maybe it's just me though!

**Comment by duckinator** [comment]
Not just you, I've definitely been thrown off by it! I noticed that when a task si in-progress, the favicon changes to be `#ff9800`. Perhaps a desaturated variant of that could work?

This is the favicon variant I'm referring to:

![cirrus-ci-favicon-orange](https://user-images.githubusercontent.com/39698/57130466-8b70df00-6d67-11e9-91cb-be88b53b4f3a.png)

**Comment by fkorotkov** [comment]
Agreed on the confusion but that orangy color it too similar to a failure IMO. What do you think about `#62b4f4` color from [Material UI Palette](https://material.io/tools/color/#!/?view.left=0&view.right=0&primary.color=64B5F6)? Seem like more neutral...

**Comment by duckinator** [comment]
@fkorotkov that's a fair point. Blue should work fine. :slightly_smiling_face:

**Comment by DanTup** [comment]
I think something yellowish might work better (I think that's what other CIs use? it's a bit traffic-light-ish), but blue still solves the main issue which is that it's easy to think it's pass :-)
