### ISSUE TITLE
Make links to task clickable by middle mouse button

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-web#245]
# Expected Behavior

I want to open different tasks from a job on cirrus-ci.com in new tabs by clicking via middle mouse button on them.

# Real Behavior

Nothing.

# Related Info

![image](https://user-images.githubusercontent.com/6510020/87963089-dbe57100-cac0-11ea-8fe9-8a7a1403500b.png)

**Comment by MarcoFalke** [comment]
As a workaround you can use normal left-click and then use the middle mouse button on the browsers' back-button

**Comment by AlexWayfer** [comment]
> As a workaround you can use normal left-click and then use the middle mouse button on the browsers' back-button

After reading your message I've remembered another more comfortable way to open links in new tabs: `Ctrl+LMB`! And it works in Cirrus-CI.com. Thank you.

But the issue is still here.

**Comment by fkorotkov** [comment]
Fixed in #470

**Comment by AlexWayfer** [comment]
> Fixed in #470

I don't see it in production. Are there anywhere deploy plans / notifications?

**Comment by fkorotkov** [comment]
Could you please try to hard refresh? It was deployed a few days ago.

**Comment by AlexWayfer** [comment]
Oh, I've got it: there is a conflict with [this Chrome extension](https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan).

As I wrote, it'd be better to have links instead of… not even buttons, spans.

OK.
