### ISSUE TITLE
Display "privileged" status of containers

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-web#269]
According to https://cirrus-ci.org/guide/linux/#kvm-enabled-privileged-containers it is possible to start "privileged" containers. However, the web view does not indicate whether a container is privileged.

I think this should be displayed for the same reason that a modified timeout, or the container name, cpu and size is displayed.

**Comment by fkorotkov** [comment]
There should be `KVM:true` or `privileged:true` labels on a task. They are not colorful but should be on a task details page.

**Comment by MarcoFalke** [comment]
Ah it is `KVM:true`. Thx
