### ISSUE TITLE
Display artifacts directly in the browser.

### ISSUE THREAD

**Issue by malena-ebert-sonarsource** [cirruslabs/cirrus-ci-web#321]
# Description
Possibility to display artifacts directly in the browser instead of downloading an archive.

# Context
If a task fails in the most cases a html report is generated and stored. To allow a quick review of the occurred issue, it is very helpful to be able to have a look into the report directly.

**Comment by fkorotkov** [comment]
This is problematic from the security perspective. Such html report can contain any JavaScript. In order to securely show the artifacts we probably need to have a separate domain. Or maybe we can use [DOMPurify](https://github.com/cure53/DOMPurify) 🤔

**Comment by RDIL** [comment]
@fkorotkov is right, assuming JS can be run, a malicious artifact could make you do something like send your Cirrus login token to the attacker.

On a side note, its really funny, I was just looking at a PR to add DOMPurify to another project when I saw this notification 😆

**Comment by malena-ebert-sonarsource** [comment]
> Such html report can contain any JavaScript.

This is the case for gradle reports.


@fkorotkov What is your concrete idea in using DOMPurify? Do you think about embedding the report in the web UI itself?
I think opening a new tab which displays the report without any additional decoration would be fine. For this a separate domain could be used.

**Comment by fkorotkov** [comment]
Should be working now. It appeared that it's possible to sandbox a page including disalowing of script execution by providing `Content-Security-Policy: sandbox` HTTP header which I just deployed.
