### ISSUE TITLE
Add a link to project build on page with specific branch builds

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-web#325]
Example: https://cirrus-ci.com/github/AlexWayfer/flame-cli/split_toys_into_gems

Current appearance:

![image](https://user-images.githubusercontent.com/6510020/99675750-a6f62480-2a88-11eb-8000-ab456aafbd1c.png)

What I'd like to see:

![image](https://user-images.githubusercontent.com/6510020/99675821-be351200-2a88-11eb-956b-e6f9acafb3ac.png)

Or maybe make an existing project title clickable.

**Comment by Eether187** [comment]
https://app.openocean.finance/referral/jEuKAbf9t9nn2xZ6rPKhw_vThZxuVjJmN4ER0gpVdgw-yN0tkEpYJsJbF25VlUG7/eth/WBTC/BUSD

**Comment by fkorotkov** [comment]
Probably we can just make this title clickable.

<img width="767" alt="Screenshot 2022-11-03 at 7 48 59 AM" src="https://user-images.githubusercontent.com/989066/199713282-626c9703-cc75-4be3-96fc-a6c98410852e.png">

**Comment by AlexWayfer** [comment]
Right now it's clickable, there was merged PR, but this issue left open.

![image](https://github.com/cirruslabs/cirrus-ci-web/assets/6510020/086b9720-83df-42ed-a1ef-609ecd4317f1)


Thank you.
