### ISSUE TITLE
Add a link to branch on a page with build

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-web#326]
Example: https://cirrus-ci.com/build/5333512213495808

Current appearance:

![image](https://user-images.githubusercontent.com/6510020/99675987-f63c5500-2a88-11eb-8d75-d3e1c2ec0a64.png)

What I'd like to see:

![image](https://user-images.githubusercontent.com/6510020/99676025-03f1da80-2a89-11eb-8c26-11d26bdb98ed.png)

**Comment by RDIL** [comment]
This is pretty easy, I'll do it in an hour or so.
