### ISSUE TITLE
Project does no longer build

### ISSUE THREAD

**Issue by swaldhoer** [cirruslabs/cirrus-ci-web#329]
I did not commit to my project for something like 2 or 3 months and now cirrus ci gets no longer triggered.

The permissons seem fine, but I do not find the repository in the list of my active project (see https://cirrus-ci.com/github/swaldhoer/native-lua). Instead there is an old project (``v``) which I deleted some time ago.

The last merge was in September and ciruss ran successfull, but since then it is broken.

Do you have an idea what is (not) going on?

Link to project: https://github.com/swaldhoer/native-lua

**Comment by fkorotkov** [comment]
I think it might be because `only_if` condition evaluates to false? 🤔

**Comment by swaldhoer** [comment]
Hm, you are correct, after commenting this line out, builds are running again...I don't fully understand it thougth, as there have been changes that show have triggered a build...but ok.

I still wonder why the project is not listed as active project (the removed project is there, and the project running again not):

![image](https://user-images.githubusercontent.com/34184299/101064208-088fb600-3594-11eb-8f61-31b6bec0eff4.png)
