### ISSUE TITLE
Memory chart?

### ISSUE THREAD

**Issue by dpo** [cirruslabs/cirrus-ci-web#353]
I stumbled on https://github.com/cirruslabs/cirrus-ci-web/pull/177, which suggests that a CPU chart and a memory usage chart should be displayed. However, in my case [1], I only see the CPU chart. I’m trying to debug runs that are getting killed, and the memory chart would help me know if the runs crashed the runner because of memory usage.

How do I enable the memory chart?

Thanks!

[1] https://cirrus-ci.com/task/5932749627326464

**Comment by fkorotkov** [comment]
Hey @dpo,

Unfortunately memory charts are only available for non-privileged containers since this information about CPU and memory is collected by Kubernetes. For VMs like FreeBSD that you have we can only display CPU at the moment.

BTW you can use up to 4G for each CPU.

**Comment by dpo** [comment]
Thank you so much for the quick reply! Is there another way to determine if memory is the cause for failure in my case? Is there a way to log into the runner or something like that?

**Comment by fkorotkov** [comment]
Unfortunately no SSH access at the moment. You can try to just give more memory or add [`on_failure` scripts](https://cirrus-ci.org/guide/writing-tasks/#execution-behavior-of-instructions) to log any debug information.

**Comment by dpo** [comment]
Thanks @fkorotkov! I’ll try the `on_failure` script! Do I need a paid plan to add more memory?

**Comment by fkorotkov** [comment]
Nope. You can use up to 8 CPUs / 32G on the free plan for OSS projects but please be responsible with so much power 😅

**Comment by dpo** [comment]
I can do that on FreeBSD VMs too? Sorry but I’m just not finding what the correct syntax is. Thanks for all your assistance?

**Comment by fkorotkov** [comment]
Yeah, take a look at how FreeBSD itself builds https://github.com/freebsd/freebsd-src/blob/main/.cirrus.yml

**Comment by dpo** [comment]
Excellent! Many thanks!
