### ISSUE TITLE
TypeError: Cannot read property 'cpu' of null

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-web#354]
Hello.

I have a tab with such URL: https://cirrus-ci.com/task/5112050227609600

But I saw just a white blank page.

Then (I'm a web-developer EZ) I opened DevTools and saw this error in the console:

```
react-dom.production.min.js:209
TypeError: Cannot read property 'cpu' of null
    at TaskExecutionInfo.tsx:41
    at Array.forEach (<anonymous>)
    at TaskExecutionInfo.tsx:39
    at TaskExecutionInfo.tsx:128
    at Go (react-dom.production.min.js:153)
    at ms (react-dom.production.min.js:261)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Zs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
```

And only on the main https://cirrus-ci.com/ page I saw that I'm not authenticated.

I thought this is the issue, but after authentication I see the same thing.

**Comment by AlexWayfer** [comment]
Also I don't understand the error in try to rerun this unavailable task: https://cirrus-ci.com/task/5674844005072896

> Task has no resources associated

**Comment by fkorotkov** [comment]
If it's a re-run of the 16 weeks old task then it's expected. We did some internal migration in preparation of open sourcing Cirrus to generalize how instances are handled and we didn't backfill data too far. If you'll push a new commit to the branch, everything should work as expected. Sorry for the inconviniences!

**Comment by AlexWayfer** [comment]
OK, thank you. So, I'd like to see more explicit pages and errors, like "Task not found (probably expired)" and "Re-run of outdated task is impossible", probably with some link to a page with explanation, dates, terms.
