### ISSUE TITLE
Don't show 0 user id

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-web#377]
<img width="709" alt="Screen Shot 2021-06-10 at 2 40 40 PM" src="https://user-images.githubusercontent.com/989066/121579625-e1f68000-c9f9-11eb-9e49-6ae12066475b.png">

**Comment by edigaryev** [comment]
What do you think about now showing these labels (starting with `canceller_*` and `rerunner_*`) at all?

**Comment by fkorotkov** [comment]
SGTM
