### ISSUE TITLE
Task show arrangement can ruin whole  repo

### ISSUE THREAD

**Issue by Apon77** [cirruslabs/cirrus-ci-web#379]
I guess, currently, the cirrus website shows a repository builds by ascending commit date. But the problem is if somehow someone does a commit with a wrong date in the future, then that commit stays on top always (even it is done by mistake)!
There is no way to revert back.  I mean if we still force push after fixing that commit date, still those mistaken build stays on top of other builds. it just misleads about the build logs. Reference:
https://cirrus-ci.com/github/ROM-builders/temporary
https://cirrus-ci.com/build/6165635127312384 (commit with future date)

So, I have a suggestion. If cirrus website ascending the tasks based on a time which is not dependent on commit date, then this problem/misleading log information in the website can be solved. Or it can be based on event time with respect to a standard timezone may be ( when it was triggered)

**Comment by iamshubh69** [comment]
Lmao
