### ISSUE TITLE
Commit title renders as `<a href="javascript:void(0)">`

### ISSUE THREAD

**Issue by MarcoFalke** [cirruslabs/cirrus-ci-web#421]
Not sure why this happens, but It might look better to not insert an `a href`.

See https://cirrus-ci.com/build/4696722466144256

![Screenshot 2022-01-02 at 17-19-54 Cirrus CI](https://user-images.githubusercontent.com/6399679/147882169-6b30d897-2c27-4517-881b-0156cae78126.png)

**Comment by obiwac** [comment]
That's quite peculiar; I'll try to figure out where this is coming from tomorrow evening.

**Comment by fkorotkov** [comment]
@obiwac I'll also take a look earlier tomorrow. Seems version of the `react-markdown` is pretty old. I'll try to upgrade it first and will see if that will fix the issue for this use case.

**Comment by obiwac** [comment]
Apparently, angle brackets in markdown are another way to write links (TIL :stuck_out_tongue:):

![image](https://user-images.githubusercontent.com/11079650/147966927-b18da1cc-7a59-4e66-a36f-52e6711e4d5e.png)

(It renders like this only when there's a colon (`:`) between the angled brackets in `react-markdown`)

In any case, this means that this is a "feature" and not a bug. Whether or not it's better if it behaves like this is another question (FWIW, I'm of the opinion is should stay as is, as I'd imagine more often someone will intend to write a link than some other string surrounded by angle brackets which happens to contain a colon). If we decide to go the "bug" route, I believe we can employ [`rehype-sanitize`](https://github.com/rehypejs/rehype-sanitize), [as suggested by `react-markdown`](https://github.com/remarkjs/react-markdown#security).

**Comment by fkorotkov** [comment]
For future researchers @obiwac referred [here](https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses) in his screenshot.

I managed to workaround the issue in #422. See https://github.com/cirruslabs/cirrus-ci-web/pull/422/commits/5b3981892e8d30ac28a218dd55330b99d7b98eee for details. @obiwac PTAL. I think it an OK workaround since it seems only affecting cases when `::` is inside the bracets.

**Comment by MarcoFalke** [comment]
Is the workaround live?

**Comment by fkorotkov** [comment]
Just deployed it.
