### ISSUE TITLE
github status for skipped tasks is "neutral" rather than "skipped"

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-ci-web#423]
Hi,

I was trying to figure out why I was getting notifications for skipped tasks (using recipe from [docs](https://cirrus-ci.org/guide/notifications/)). Which lead to me to notice that 'skipped' tasks are reported as 'neutral'.

See e.g. https://github.com/anarazel/pg-vm-images/actions/runs/1675247872 - note how
https://github.com/anarazel/pg-vm-images/runs/4755809197?check_suite_focus=true says "neutral" in "Cirrus CI neutral on main branch" - even though https://cirrus-ci.com/build/4782212045340672 succeeded.

Looking at https://docs.github.com/en/rest/reference/checks#check-suites it seems that should be "skipped" instead?

Now, that'd still not fix the wrong "failed" notification, but that's a separate problem :)

Regards,

Andres

**Comment by fkorotkov** [comment]
Indeed [`conclusion`](https://docs.github.com/en/rest/reference/checks#create-a-check-run) now can be `skipped`. Initially there were no `skipped`, `stale` and `timed_out` conclusions. Seems they were added recently. Will make the change shortly.

What about your 

> wrong "failed" notification

? Can you elaborate?

**Comment by anarazel** [comment]
Hi, 

On January 9, 2022 7:42:54 PM PST, Fedor Korotkov ***@***.***> wrote:
>Indeed [`conclusion`](https://docs.github.com/en/rest/reference/checks#create-a-check-run) now can be `skipped`. Initially there were no `skipped`, `stale` and `timed_out` conclusions. Seems they were added recently. Will make the change shortly.
>
>What about your 
>
>> wrong "failed" notification
>
>? Can you elaborate

Sure. I just mean that because the documented notification workflow does `if conclusion != 'success'`, it'll report a failure even if skipped instead of neutral is used.

Regards,

Andres
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
