### ISSUE TITLE
Create Persistent Worker Pool 

### ISSUE THREAD

**Issue by stupid-kid-af** [cirruslabs/cirrus-ci-web#427]
Create Persistent Worker Pool
Create button not working

I got this error
![image](https://user-images.githubusercontent.com/54206927/150512448-bd9571fe-2708-4dd2-91ce-60d43ca5fafb.png)

**Comment by edigaryev** [comment]
Closed in favor of https://github.com/cirruslabs/cirrus-ci-docs/issues/964.

**Comment by stupid-kid-af** [comment]
It works perfectly.
Thanks for your support.
