### ISSUE TITLE
UI/UX: distinguish between fail and abort with a different color

### ISSUE THREAD

**Issue by RandyMcMillan** [cirruslabs/cirrus-ci-web#433]
It would be great to distinguish between a fail and an abort with a different color.
When testing - I may abort several tests to save time/processing/etc...
When viewing a session - it would really be great to quickly see which tests were aborted and which failed.
Currently - I have to click on each one to remember which tests I aborted. When running tests on different repos this becomes tedious. I can only image others would agree. 

Thanks for your time! And great service! 

RM  

![Screen Shot 2022-02-06 at 12 28 08 PM](https://user-images.githubusercontent.com/152159/152693280-1679a3be-3068-4879-9006-5cac8837357d.png)

**Comment by fkorotkov** [comment]
Colors are actually a little different but not subtle enough. I think having different icons is a better approach:

<img width="111" alt="Screen Shot 2022-02-06 at 12 43 33 PM" src="https://user-images.githubusercontent.com/989066/152693801-4dd47ede-e9e7-4ae1-92f9-b9c50e1c117c.png">

The change will be available after a few minutes after master build will build the Docker image.
