### ISSUE TITLE
URL not configured properly

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#44]
URL Vulnerability: HTTP & HTTPS protocols works apart and return the same page content
URL Vulnerability: www / non-www page redirects are not configured
URL Vulnerability: 200 - Error page is incorrect
URL Vulnerability: Configured wrong

**Comment by fkorotkov** [comment]
Where it's coming from?

**Comment by RDIL** [comment]
https://sitechecker.pro/seo-report/https://cirrus-ci.com : `Search Optimization` section

**Comment by RDIL** [comment]
It seems like the `https` is only broken on the landing page.

**Comment by RDIL** [comment]
#45 fixes the second and third issues on the list

**Comment by RDIL** [comment]
If I remember correctly, I think there is an easy way to redirect http to https on the landing page with a 301

https://support.google.com/webmasters/answer/6073543?hl=en

**Comment by fkorotkov** [comment]
BTW this headers should instruct browsers to use only HTTPS https://github.com/cirruslabs/cirrus-ci-web/blob/master/serve.json#L15-L16

**Comment by RDIL** [comment]
I found some extra headers which may help.  Will add them now.

**Comment by RDIL** [comment]
(Source: https://github.com/GoogleCloudPlatform/flask-talisman)

**Comment by RDIL** [comment]
@fkorotkov do you know where the location of the SSL certificate's PEM is on the server?

**Comment by RDIL** [comment]
I assume this is running on a Kubernetes cluster, not a specific type of web server (e.g. Apache or Nginx), which is going to make this a bit harder 😓

**Comment by fkorotkov** [comment]
It's under Google's magical HTTP load balancer so there is no easy access to the certificate. Why do you need it?

**Comment by RDIL** [comment]
Was considering a solution where node sends the cert if on http.

**Comment by RDIL** [comment]
UPDATE: When not logged in, HTTPS does not seem to be forced on homepage (but is possible to connect with it).
