### ISSUE TITLE
API token never displayed after generation

### ISSUE THREAD

**Issue by berrange** [cirruslabs/cirrus-ci-web#452]
In the page  `https://cirrus-ci.com/settings/<repo path>`  there is the `API Settings` panel for handling API tokens.

I press the `Generate new token` button and it does nothing visible at all, but when I manually reload I see a new API token has indeed been created. This is useless though, because I can only see the last 6 characters of the new token, the full token was never displayed to me.

The only way I've been able to get the API token is in Firefox - `Hamburger menu -> More Tools -> Web developer tools`. Then hit `Generate new token`. The HTTP request is captured and I can look at the JSON response document to get the token.

I've experienced this problem in Firefox on Linux, but a colleague has reproduced on Safari, Chrome & Firefox on both macOS, iIOS and Linux.

**Comment by c3d** [comment]
I am the colleague who reported this to @berrange initially. I tested on:

- Firefox under Linux (Fedora ARM)
- Safari and Chrome under macOS
- Safari under iOS

They all give me the same result.

**Comment by fkorotkov** [comment]
Please try to hard refresh to invalidate caches. A fix has been just deployed. Sorry for the inconviniences.

**Comment by berrange** [comment]
Yes, that worked after a forced refresh (shift reload) in Firefox

**Comment by fkorotkov** [comment]
Thank you for verifying! 🙌

**Comment by c3d** [comment]
@fkorotkov Verified on all the browsers where it failed before.
