### ISSUE TITLE
Show unique labels on mobile

### ISSUE THREAD

**Issue by cevich** [cirruslabs/cirrus-ci-web#46]
From the POV of github "Checks" tab and cirrus 'task' page, it's easy to see what matrix values are being used.  However, from the 'build' page, each task only shows it's name.  When testing with a large-ish matrix, this makes it difficult to pick out a specific 'task' to view for more details.  It would be helpful for debugging, if the 'view all tasks' (i.e. build page) showed the unique matrix values for each item.

For example, if I have a ``testing_task`` with a ``matrix:`` across ``image_name``, I would like to see the name of the image listed next to each ``testing`` task-link in the`` https://cirrus-ci.com/build/$CIRRUS_BUILD_ID`` page.

**Comment by fkorotkov** [comment]
Moved the issue to `cirrus-ci-web` repo and changed the title a little bit. Will see if it's possible to fit these labels on such small screens.

**Comment by fkorotkov** [comment]
I think it got implemented already at some point. 😅
