### ISSUE TITLE
Update GraphiQL

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-web#463]
v2 of graphiql is out and it supports dark theme! We should update it and try to match with our style so https://cirrus-ci.com/explorer is prettier.

**Comment by BigiSmalz** [comment]
what should we do exactly?

**Comment by fkorotkov** [comment]
Just run `yarn up graphiql` and tweaking `/explorer` styles. I tried it and seems height of the editor is not correct.
