### ISSUE TITLE
Active Repository Remains Undetected after providing relevant permissions

### ISSUE THREAD

**Issue by kdrag0nX** [cirruslabs/cirrus-ci-web#492]

**Comment by fkorotkov** [comment]
Do you have any commits by you pushed to the default branches of the repositories? An active repository is the one that your user committed to.

**Comment by kdrag0nX** [comment]
> Do you have any commits by you pushed to the default branches of the repositories? An active repository is the one that your user committed to.

Thanks Fedor, this issue was solved yesterday , after committing to the repo!
