### ISSUE TITLE
Frontend broken on task page

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#500]
https://cirrus-ci.com/task/5500273565630464 won't load. It just goes blank.

**Comment by fkorotkov** [comment]
Fixed in [8f2bd0d](https://github.com/cirruslabs/cirrus-ci-web/commit/8f2bd0df72f178f4d9fed61f3154a5bf3bf4081d) and #502 will prevent it from happening again. Not sure why the compilation is not strict to begin with. 🤦‍♂️
