### ISSUE TITLE
Deleted repository still shown on the UI

### ISSUE THREAD

**Issue by bcecchinato** [cirruslabs/cirrus-ci-web#503]
Hello !

I've delete these two repositories : 4511195714027520 and 5871226430160896 but they are still shown on the UI.

Am I missing something ?

**Comment by fkorotkov** [comment]
Hey @bcecchinato,

The deletion is not immediate and you repositories might have been still cached for an hour or two after you deleted them. I see it's being deleted now and you shouldn't be able to see them.

**Comment by bcecchinato** [comment]
@fkorotkov the deletion is already few days ago. I tried in private mode but i still see the repositories. On the graphiql explorer i have the repositories in the topActives ones.

hope that helps

**Comment by fkorotkov** [comment]
Indeed! There was an issue that a GraphQL connection was not handled properly. So you could still see the edges but upon a click everything worked as expected. The GraphQL connection regression was fixed and have been just deployed. You shouldn't see them anymore. Sorry for inconviniences!

**Comment by bcecchinato** [comment]
yes the problem is fixed ! Thanks as usual :)
