### ISSUE TITLE
Account Settings shows "Can't find information this organization!"

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-ci-web#510]
If I click my avatar in the top-right, then click "Account Settings", I get this:

![image](https://user-images.githubusercontent.com/39698/215222616-6b153ff1-6dab-4165-be79-83efe4cfbcef.png)

If I click the gear icons by any of those, it says "Can't find information this organization!":

![image](https://user-images.githubusercontent.com/39698/215222423-e3ab5951-8546-468f-992d-2c714c64b6f3.png)

And, notably, if I hover over the GitHub icon to the left of "Account Settings", the URL is shown to be `https://cirrus-ci.com/undefined/undefined`:

![image](https://user-images.githubusercontent.com/39698/215222772-dd2c3fec-03e1-40d2-a119-634c562c9385.png)

**Comment by fkorotkov** [comment]
Should work for you now. Sorry for the inconviniences!

**Comment by duckinator** [comment]
Confirmed it's working again, thanks for the quick fix!
