### ISSUE TITLE
API: statusTimestamp undefined

### ISSUE THREAD

**Issue by edsantiago** [cirruslabs/cirrus-ci-web#554]
Currently flaking: about one out of three API calls succeeds, the rest fail.
```
query {
    build(id: 5116431809904640) {
      id, status,tasks {
        id,name,labels,status,statusTimestamp,commands {
          name,type,status
        },notifications { level, message }, statusDurations {status durationInSeconds }
      }
    }
  }
```
```
{
  "errors": [
    {
      "message": "Validation error of type FieldUndefined: Field 'statusTimestamp' in type 'Task' is undefined @ 'build/tasks/statusTimestamp'",
      "locations": [
        {
          "line": 4,
          "column": 31
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    }
  ],
  "data": null
}
```
statusTimestamp has been working for me for years. It started flaking today.

**Comment by fkorotkov** [comment]
@edsantiago Sorry for the inconvenience! 

We removed `statusTimestamp` because it seemed like a weird filed that was added by accident years ago. `statusTimestamp` was representing "timestamp of the current status of the task". What do you use it for?

**Comment by fkorotkov** [comment]
In the meantime we've revert the change.

**Comment by edsantiago** [comment]
No worries, thank you for the quick response! I have a flake catalogger (cataloguer?), it basically runs the above query on merged PR, looking for tasks where status=FAILED. (The implication is that those are flakes, because to merge we need a clean CI run). `statusTimestamp` is useful to identify network-or-registry flakes, because those timestamps will typically cluster together. The timestamp is also helpful to identify when a job flaked: was it 2 weeks ago but the PR only just merged today? If so, the flake-fix may already have been merged, just, that job was origin'ed on a too-old base.

It's not absolutely essential, though. If it's costly to maintain, please go ahead and remove it.

**Comment by fkorotkov** [comment]
I think `finalStatusTimestamp` field will give you the same result as you expect from a `FAILED` task. Could you please switch from `statusTimestamp` to `finalStatusTimestamp` at some point so we can cleanup the weird field? There is no rush since it's not costly to maintain but will be good to have.

**Comment by edsantiago** [comment]
So done. I made the change this afternoon, and have tested it against all PRs from the last few hours, and all looks well. I consider this resolved, please feel free to re-remove `statusTimestamp`.

Thank you again.
