### ISSUE TITLE
Log message output line numbers, highlighting, and URL link referencing

### ISSUE THREAD

**Issue by ppaulweber** [cirruslabs/cirrus-ci-web#63]
Hello, it would be great to see in the `cirrus-ci` task/script log messages the output line numbers. Moreover the possibility to highlight one line or a line range of those log messages to reference the log line(s) in question via URL just like in `travis-ci`, `concourse-ci` etc.

Proposed URL link reference syntax: 
- line reference
  - task-based
    `https://cirrus-ci.com/task/<id>#L<integer>` 
  - or script-based
    `https://cirrus-ci.com/task/<id>/<scriptname>#L<integer>` 

- line range reference
  - task-based
    `https://cirrus-ci.com/task/<id>#L<integer>-#L<integer>` 
  - or script-based
    `https://cirrus-ci.com/task/<id>/<scriptname>#L<integer>-#L<integer>` 

Reference examples of travis-ci:
- line reference
  https://travis-ci.org/casm-lang/libstdhl/jobs/407556254#L551
- line range reference
  https://travis-ci.org/casm-lang/libstdhl/jobs/407556254#L559-L564

**Comment by ppaulweber** [comment]
:tada:

**Comment by cevich** [comment]
This is fantastic, thanks guys!
