### ISSUE TITLE
Web Notifications

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-web#68]
Need to implement a service worker that subscribes to build status updates of a user and pushes notifications if any of the builds failed.

**Comment by RDIL** [comment]
+1

**Comment by geekflyer** [comment]
I just had a similar thought. What I particular would be the ability to go on a task instance page like https://cirrus-ci.com/task/6206501067161600 and be able to ad-hoc subscribe to updates (i.e. task started, task failed, completed) of a single task. I don't necessarily want to subscribe permanently to an entire repo.

**Comment by fkorotkov** [comment]
I was thinking about just subscribing to **your builds** (builds initialized by your user) only when they succeed/fail.

Subscribing to arbitrary tasks/builds if their details page are open in the browser does sound good too. 🙌

**Comment by fkorotkov** [comment]
Cirrus CI pushes updates via a websoket to `user-build-update-$userId` topic for similar to how Cirrus subscribes to `build` and `task` updates in [`src/rtu/ConnectionManager.ts`](https://github.com/cirruslabs/cirrus-ci-web/blob/e6e85f4db6f07d94b0eb638de1b7572be276845a/src/rtu/ConnectionManager.ts#L46).

**Comment by probonopd** [comment]
> Cirrus CI pushes updates via a websoket

Do you have an example on how to subscribe to that, e.g., using PyQt5?

**Comment by fkorotkov** [comment]
The notifications part was fixed in #298 vie Web Notifications spec so notifications will be shown even if there is no Cirrus tag is open. So closing this issue.

@probonopd what exactly you want to achive? Getting notification for youself or getting updated for a particular repository? There are couple of options now of how you can get notified.

**Comment by probonopd** [comment]
I would like to see a desktop (browser) notification whenever something happens to
a) any of my projects' builds
b) random projects' builds I have explicitly subscribed to

**Comment by fkorotkov** [comment]
For you own builds Web Notifications will work the best. For a custom repository you can try CCTray integration: https://twitter.com/cirrus_labs/status/1235566393724026880

**Comment by probonopd** [comment]
Thank you very much @fkorotkov. cctray is better than what I would have dreamed of.

Would it be possible to subscribe to all repositories of an user or organization?
E.g., in addition to 

```
https://api.cirrus-ci.com/github/<USER OR ORGANIZATION>/<REPOSITORY>/cctray.xml
```

also allow for

```
https://api.cirrus-ci.com/github/<USER OR ORGANIZATION>/cctray.xml
```

https://cirrus-ci.org/guide/writing-tasks/#cctray-xml

**Comment by fkorotkov** [comment]
Could you please create a separate issue about the cctray part and I'll take a look at what needs to be added from Cirrus side.
