### ISSUE TITLE
Logs don't show up while task is runnning

### ISSUE THREAD

**Issue by dnfield** [cirruslabs/cirrus-ci-web#70]
If a task is running, and you expand the section for it, the logs don't show up.  You have to wait until the task finishes.

Occasionally it seems to work if you expand it at just the right time (?).

**Comment by fkorotkov** [comment]
Do you expand the section before it starts executing? 

BTW work on https://github.com/cirruslabs/cirrus-ci-docs/issues/138 will include some improvements for realtime logs as well.

**Comment by dnfield** [comment]
Yes, still nothing

**Comment by fkorotkov** [comment]
#138 should've help with that since now Cirrus is additionally caching tasks while they are streamed.

**Comment by dnfield** [comment]
Yes, this seems to be fixed now, thanks!
