### ISSUE TITLE
httpd: specify encoding for text/plain logs

### ISSUE THREAD

**Issue by edsantiago** [cirruslabs/cirrus-ci-web#72]
Log files produced by ginkgo use Unicode bullets and checkmarks; these render poorly in Firefox, which ([for reasons of their own](https://unix.stackexchange.com/questions/308469/how-to-set-fallback-encoding-to-utf-8-in-firefox)) refuse to add a "default to UTF-8" setting for text/plain.

Would you consider amending your httpd settings to add `; charset=utf-8` to the `Content-Type` header?
```
curl --head https://api.cirrus-ci.com/v1/task/5713695240355840/logs/main.log
HTTP/1.1 200 OK
Date: Thu, 11 Jul 2019 14:46:13 GMT
Content-Type: text/plain      <<<--------- here
Content-Length: 0
Via: 1.1 google
Alt-Svc: clear
```
Thank you for your consideration.

**Comment by fkorotkov** [comment]
```bash
$: curl --head https://api.cirrus-ci.com/v1/task/5713695240355840/logs/main.log
HTTP/2 200 
date: Thu, 11 Jul 2019 16:48:10 GMT
content-type: text/plain;charset=utf-8
content-length: 0
via: 1.1 google
alt-svc: clear
```
