### ISSUE TITLE
What does a pull request screen show? 🤔

### ISSUE THREAD

**Issue by aslushnikov** [cirruslabs/cirrus-ci-web#8]
The URL: https://cirrus-ci.com/github/GoogleChrome/puppeteer/pull/2204
![image](https://user-images.githubusercontent.com/746130/37499637-0af2ecf4-2882-11e8-88f6-8f534b9d6d48.png)

There's a huge green bar in the middle of screen. I don't understand what it means and if it's of any interest for me.

**Comment by fkorotkov** [comment]
This is a chart with recent build durations. I've changed it to be shown only for > 10 builds, added Y axis and some tooltips. For example, you can check it out for your master branch: https://cirrus-ci.com/github/GoogleChrome/puppeteer/master
