### ISSUE TITLE
Dev guide out of date

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#81]
We should probably:
* Move dev guide to `CONTRIBUTING.md`

cc @geekflyer

**Comment by geekflyer** [comment]
I updated the readme a bit as part of my typescript PR.
However what is missing is some info on how to run the UI locally against the API as an authenticated user. I personally manipulated the cookie domain of the cookies from api.cirrus-ci.com to work on localhost, but not sure if that's the best and easiest way to do so.
