### ISSUE TITLE
UX issues / improvements

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-web#87]
Just collecting some UX issues / thoughts that I encounter while using cirrus. Once the TypeScript PR merged I might work on some of them:

- [x] Link from repository to github (currently only commits are linked, but repo view is not).
- [ ] Add link to `.cirrus.yml` that was used or a given build
- [x] Updates / subscriptions (e.g. live logs and script completion status) in task view are extremely unreliable, UI often gets stale. tracked separately in #88 
- [ ] Make it easier / more intuitive to navigate to organization view
- [ ] Fix missing / broken repo list in organization view
- [ ] Add various search and filtering capabilities
- [x] Show a timestamp everywhere something (build, task, script) was started
- [x] Auto open drawer when that script is executing (example: if mycoolscript is running, the mycoolscript accociated drawer opens then when it finishes it auto closes)

**Comment by RDIL** [comment]
Everything but 3 sounds good ... the websockets keep disconnecting which makes it difficult.

**Comment by fkorotkov** [comment]
They are reconnecting though. I did notice the lags on TaskDetails page only though. On the home page and BuildDetails page statuses are updating as expected for me.

**Comment by RDIL** [comment]
True.  3 is still a valid bug though.

**Comment by RDIL** [comment]
One thing that could also be added to this list: https://github.com/cirruslabs/cirrus-ci-docs/issues/161 - suggestion 1
