### ISSUE TITLE
UI live updates unreliable

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-web#88]
Let's create a separate issue to discuss the live update reliability issues in the UI.

As @fkorotkov already mentioned in #87 the issues are mainly in the Task Details view, but there may be other places.

### Short summary of the problem:
Often times when one is a specific cirrus-ci page, e.g. the task details view, and a task is still in running state and as the task progresses the UI does not properly update the data (gets stale).

In detail this may be::
- step status is not updated (e.g. step is shown as executing for many seconds, even though it has already completed or failed a long time ago)
- live logs are stuck

Typically the only way to get out of this situation is to refresh the browser.
(Personally in fact I'm refreshing my browser a lot when I'm on the task view since I don't trust the live updates to work).

As mentioned by @fkorotkov and @RDIL the issue seems to have something to do with websockets connections breaking up. Most of the data there is retrieved via graphql subscriptions which use websockets.

Here are some of the action items to make this a better experience:
1. Investigate what's the root cause of the unreliable websockets connection. If possible mitigate it. Check how other CI/CD systems do the live logs reliably (for example gitlab is relatively reliable with respect to that and their code is open source so we can have a peek. Drone is another option to peek at).
2. Give a visual indication of the connection status. If we lose tell that to the user. Also indicate when we attempt reconnect. Basically make sure the user knows whats going on instead of waiting minutes for a "script" to complete, whereas in reality in already completed long time ago.
3. In case we lost the websocket connection and have to reconnect, make sure there is a mechanism which fetches / recovers the data that has been lost while the connection was down. I.e. if we lose connection 5 seconds, it is not acceptable to lose script status or log updates that happened during those 5 seconds.

@fkorotkov @RDIL any other thoughts / things I missed on this?

**Comment by geekflyer** [comment]
As for reverse engineering how other ci/cd systems do it, we can simulate broken and slow brow connections via the Chrome network tab and by disabling wifi temporarily etc.

**Comment by RDIL** [comment]
This summary contains most of my thoughts.  Travis is also an option to peak at ([this](https://github.com/travis-ci/travis-web) should be it).

A few things worth mentioning:
* Possibly related bug: `[Object object]` appears in logs (confirmed for different langs and raw logs from build machine instead of UI don't contain it)
* I feel like the websockets breaking up is why some data is getting leaked to nowhere instead of delivered to the client
* Maybe we could employ auto-refreshing of the page when it is detected that the websockets break up?
* **There was some old issue for this matter (written by me) that may help with other details**

**Comment by geekflyer** [comment]
ref #83 #70

**Comment by geekflyer** [comment]
@RDIL which old issue for the details are you referring to?

**Comment by fkorotkov** [comment]
As far as I know Travis and Circle are using Pusher for the live updates.

[`ConnectionManager.ts#open`](https://github.com/cirruslabs/cirrus-ci-web/blob/master/src/rtu/ConnectionManager.ts#L12) should resubscribe to topics and a result subscriber should receive fake [`reconnect` event](send) which causes a component to refresh.

**Comment by RDIL** [comment]
I think I made some issue back in January about this.
Can't seem to find it now.

**Comment by geekflyer** [comment]
@fkorotkov  I'm not sure if I'm doing something wrong but I tried to debug the subscription stuff a bit and as far as I can see it the websocket connection keeps alive just fine. Also the UI sends a bunch of subscription events to the backend. However no matter what I did, it seems the backend never send a single message for anything. So maybe this is rather a backend issue?

**Comment by fkorotkov** [comment]
There might be an issue in it. The micro services responsible for real-time updates were a little over-engineered with an ability to handle any amount of updates in a multi-zone setup. 😅😓Had an idea for a long time how to simplify it and make it easier to debug such issues. Will check it next week.

**Comment by geekflyer** [comment]
just a thought, wouldn't usage of Cloud Firestore in Native mode also help with this (i.e. realtime updates on any data)?

**Comment by fkorotkov** [comment]
It will! Though about it too... Unfortunately, there is no easy way of migration from Datastore to Native. Also it will block creating self-hosted edition of Cirrus for on prem installation. Right now there Cirrus only requires a very simple key-value storage and very simple pup/sub for functioning.

**Comment by geekflyer** [comment]
I see. Anyways, would be cool if you can address this issue soon. This issue is currently imho the biggest "gotcha" with cirrus. Wouldn't be surprised if some potential users are deterred mainly because of this :)

**Comment by geekflyer** [comment]
hey folks, I just wanted to clarify that currently (i.e. at least since 1 week) live updates don't work at all for me. I.e. neither task / build updates nor the real time logs work at all (not just unreliable, they just never at all). I initially thought they're just unreliable (and afaik they actually used to work half of the time a few weeks / months ago), but apparently now they're completely broken 💔. 😉

Just wanted to confirm if that's the same behavior you're getting @RDIL @fkorotkov, or if this may be another data problem in my org?

**Comment by fkorotkov** [comment]
@geekflyer seems working for me but definitely not as smoothly as before. 😪I've almost finished the new implementation of streaming updates. Hopefully will finish testing and deploy it today.

**Comment by fkorotkov** [comment]
@geekflyer just deployed the new backed for real-time updates. Please let me know how it works for you. 🙌

**Comment by geekflyer** [comment]
ok awesome, this seems to work now!
Only complaint I have is that somehow the log lines always end with [Object object] so there must be another small bug somewhere (not sure if thats backend or frontend though).

**Comment by fkorotkov** [comment]
This should be a front end when websocket reconnects. Will take a look...

**Comment by RDIL** [comment]
holy moly this is the best the logs have ever been just now :O
