### ISSUE TITLE
Inconsistent check statuses, builds randomly cancelled on Flutter repo

### ISSUE THREAD

**Issue by bkonyi** [cirruslabs/cirrus-ci-web#94]
We're relying on Cirrus checks for some tooling in the Flutter engine repository that waits for the checks to go green before merging a PR but it seems that the checks have been unreliable as of late.

The main issue I've been seeing lately is that jobs are being cancelled almost immediately after a PR is created:

![image](https://user-images.githubusercontent.com/24210656/62386054-932d5480-b50b-11e9-9d32-28957ee1075e.png)

Upon further investigation, it appears that the jobs are being cancelled due to a "newer PR build", although no further commits were submitted for that PR.

![image](https://user-images.githubusercontent.com/24210656/62386143-d982b380-b50b-11e9-81a3-f894f7bc61be.png)

Is there any reason in particular why this is happening?

Another thing I've been seeing is that there appears to be duplicate entries for each Cirrus build on the PR, and often their statuses don't match. When the PR is first created, some checks are marked as failing and eventually stabilize once builds actually start. Is there any particular reason why these duplicates are there or why their states are rather volatile when a PR is created? I've been able to work around this behavior up until this point, but it makes it rather hard to build tooling around Cirrus checks.

Thanks in advance!

**Comment by fkorotkov** [comment]
@bkonyi do I understand it correctly that this PR was created automatically via a bot, the bot creates a branch, then **immediatly** creates a PR from it and waits for checks for PR to finish?

**Comment by fkorotkov** [comment]
I've tweaked the logic so now you shouldn't see the status check flip because of the cancelation.

**Comment by bkonyi** [comment]
> @bkonyi do I understand it correctly that this PR was created automatically via a bot, the bot creates a branch, then **immediatly** creates a PR from it and waits for checks for PR to finish?

Ah, yes, that sounds right... I guess the push to a new branch triggers Cirrus to run and then the creation of the PR triggers them again?

Either way, thanks for the quick response! I'll let you know if I'm still seeing problems.

**Comment by fkorotkov** [comment]
> Ah, yes, that sounds right... I guess the push to a new branch triggers Cirrus to run and then the creation of the PR triggers them again?

Exactly. PR builds are treated differently so you have `CIRRUS_PR` environment variable in case you need to customize logic of your CI scripts
